[log]
  level = "DEBUG"

[providers]
  [providers.file]
    directory = "/data"
    watch = true

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"

# [http.middlewares]
#   [http.middlewares.redirect-https.redirectScheme]
#     scheme = "https"

[certificatesResolvers.le.acme]
  email = "alpha@kejadlen.dev"
  storage = "/data/acme.json"
  [certificatesResolvers.le.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"

[api]
  insecure = true
